# Generated by Django 4.2.6 on 2024-04-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliberasaun',
            fields=[
                ('no_cafi', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('linha_ministerio', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=255)),
                ('data_cafi', models.DateField()),
                ('observasaun', models.TextField()),
                ('file_attachment', models.FileField(upload_to='deliberasaun/')),
            ],
            options={
                'verbose_name': 'deliberasaun',
                'verbose_name_plural': 'deliberasaun',
            },
        ),
    ]
