# Generated by Django 4.2.6 on 2024-04-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliberasaun_cafi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliberasaun',
            name='no_cafi',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
