# Generated by Django 5.0 on 2025-06-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliberasaun_cafi', '0002_alter_deliberasaun_no_cafi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliberasaun',
            name='asunto',
            field=models.TextField(max_length=1000),
        ),
    ]
