# Generated by Django 5.0 on 2025-07-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliberasaun_cafi', '0003_alter_deliberasaun_asunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliberasaun',
            name='anexo',
            field=models.FileField(default=None, upload_to='anexo'),
            preserve_default=False,
        ),
    ]
