# Generated by Django 5.0 on 2025-07-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ata', models.CharField(max_length=50, unique=True)),
                ('linha_ministerio', models.CharField(max_length=50)),
                ('asunto', models.TextField(max_length=1000)),
                ('data_ata', models.DateField()),
                ('diversos', models.CharField(max_length=200)),
                ('file_attachment', models.FileField(upload_to='ata/')),
            ],
            options={
                'verbose_name': 'ATA Reuniaun',
                'verbose_name_plural': 'ATA Reuniaun',
            },
        ),
    ]
