# Generated by Django 4.2.6 on 2024-04-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KartaSai',
            fields=[
                ('no_karta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('no_referensia', models.CharField(max_length=20)),
                ('data_karta', models.DateField()),
                ('data_sai', models.DateField()),
                ('asunto', models.CharField(max_length=255)),
                ('dirije_ba', models.CharField(max_length=50)),
                ('linha_ministerio', models.CharField(max_length=50)),
                ('file_attachment', models.FileField(upload_to='karta_sai/')),
            ],
            options={
                'verbose_name': 'Karta Sai',
                'verbose_name_plural': 'Karta Sai',
            },
        ),
        migrations.CreateModel(
            name='KartaTama',
            fields=[
                ('no_karta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('no_referensia', models.CharField(max_length=20)),
                ('data_karta', models.DateField()),
                ('data_tama', models.DateField()),
                ('asunto', models.CharField(max_length=255)),
                ('despacho', models.CharField(max_length=50)),
                ('linha_ministerio', models.CharField(max_length=50)),
                ('file_attachment', models.FileField(upload_to='karta_tama/')),
            ],
            options={
                'verbose_name': 'Karta Tama',
                'verbose_name_plural': 'Karta Tama',
            },
        ),
    ]
