# Generated by Django 5.0 on 2025-06-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karta_cafi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartatama',
            name='asunto',
            field=models.TextField(max_length=500),
        ),
    ]
