# Generated by Django 5.0 on 2025-07-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karta_cafi', '0002_alter_kartatama_asunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaCafi',
            fields=[
                ('no_karta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('no_referensia', models.CharField(max_length=20)),
                ('data_reuniaun', models.DateField()),
                ('data_sai', models.DateField()),
                ('asunto', models.CharField(max_length=255)),
                ('dirije_ba', models.CharField(max_length=100)),
                ('linha_ministerio', models.CharField(max_length=100)),
                ('file_attachment', models.FileField(upload_to='karta_sai/')),
            ],
            options={
                'verbose_name': 'Karta Sai',
                'verbose_name_plural': 'Karta Sai',
            },
        ),
        migrations.CreateModel(
            name='ConviteCafi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_referensia', models.CharField(max_length=20)),
                ('data_convite', models.DateField()),
                ('asunto', models.TextField(max_length=500)),
                ('dirije_ba', models.CharField(max_length=100)),
                ('linha_ministerio', models.CharField(max_length=100)),
                ('file_attachment', models.FileField(upload_to='karta_tama/')),
            ],
            options={
                'verbose_name': 'Karta Tama',
                'verbose_name_plural': 'Karta Tama',
            },
        ),
        migrations.DeleteModel(
            name='KartaSai',
        ),
        migrations.DeleteModel(
            name='KartaTama',
        ),
    ]
