# Generated by Django 5.0 on 2025-07-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karta_cafi', '0003_agendacafi_convitecafi_delete_kartasai_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendacafi',
            options={'verbose_name': 'Agenda Cafi', 'verbose_name_plural': 'Agenda Cafi'},
        ),
        migrations.AlterModelOptions(
            name='convitecafi',
            options={'verbose_name': 'Convite Cafi', 'verbose_name_plural': 'Convite Cafi'},
        ),
    ]
